# Generated by Django 5.2.7 on 2025-10-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=150, unique=True, verbose_name="Email"),
                ),
                (
                    "s_o_name",
                    models.CharField(
                        max_length=200, verbose_name="Фамилия Имя Отчество"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["email", "s_o_name"],
            },
        ),
        migrations.CreateModel(
            name="MailingsAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Время попытки рассылки"),
                ),
                (
                    "status_new",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "post_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ["start_time", "status_new", "post_response"],
            },
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=150, verbose_name="Тема письма"),
                ),
                ("text", models.TextField(max_length=900, verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
                "ordering": ["subject", "text"],
            },
        ),
        migrations.CreateModel(
            name="Mailings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_send",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время начало рассылки"
                    ),
                ),
                (
                    "end_send",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время окончание рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("end_at", "Завершена"),
                            ("created_at", "Создана"),
                            ("start_at", "Запущена"),
                        ],
                        default="created_at",
                        max_length=15,
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        to="newsletter.client", verbose_name="Получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["first_send", "end_send", "status", "text", "owner"],
            },
        ),
    ]
