# Generated by Django 5.2.7 on 2025-10-30 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("newsletter", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailings",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailingsattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="newsletter.mailings",
                verbose_name="Письмо",
            ),
        ),
        migrations.AddField(
            model_name="mailings",
            name="text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="newsletter.messages",
                verbose_name="Сообщение",
            ),
        ),
    ]
