# Generated by Django 5.2.7 on 2025-10-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailings",
            name="status",
            field=models.CharField(
                choices=[
                    ("end_at", "Завершена"),
                    ("created_at", "Создана"),
                    ("start_at", "Запущена"),
                ],
                default="Создана",
                max_length=15,
            ),
        ),
    ]
