# Generated by Django 5.2.7 on 2025-10-31 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_alter_mailings_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailings",
            old_name="client",
            new_name="clients",
        ),
    ]
