# Generated by Django 5.2.7 on 2025-11-01 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_rename_client_mailings_clients"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mailings",
            new_name="Mailing",
        ),
        migrations.RenameModel(
            old_name="MailingsAttempt",
            new_name="MailingAttempt",
        ),
        migrations.RenameModel(
            old_name="Messages",
            new_name="Message",
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["first_send", "end_send", "status", "text", "owner"],
                "permissions": [
                    ("can_all_view_mailing", "Просмотр всех рассылок"),
                    ("can_delete_mailing", "Удаление рассылки"),
                    ("can_update_mailing", "Обновление рассылки"),
                    ("can_create_mailing", "Добавление рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["start_time", "status_new"],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
