# Generated by Django 5.2.7 on 2025-11-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_rename_mailings_mailing_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": [
                    "first_send",
                    "end_send",
                    "status",
                    "text_message",
                    "owner",
                ],
                "permissions": [
                    ("can_all_view_mailing", "Просмотр всех рассылок"),
                    ("can_delete_mailing", "Удаление рассылки"),
                    ("can_update_mailing", "Обновление рассылки"),
                    ("can_create_mailing", "Добавление рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="text",
            new_name="text_message",
        ),
    ]
