# Generated by Django 5.2.7 on 2025-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0007_message_owner_alter_message_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время попытки рассылки"
            ),
        ),
    ]
